version: '1.0.1-dev-{build}'
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
  - dotnet restore
build_script:
  - dotnet build --no-restore -c Release
  - ps: nuget pack -properties version=$Env:APPVEYOR_BUILD_VERSION
test_script:
  - ps: |
      cd test
      dotnet test --no-restore -c Release
      cd ../
artifacts:
  - path: '**\*.nupkg'
    name: package
    type: NuGetPackage
deploy:
  provider: NuGet
  api_key:
    secure: lEbBqFe17CfAfPuaLZLV7eli2hhs2c0qU2TAjq5uFHFZs2Od8CPYTc63lIzjYRn3
  skip_symbols: false
  artifact: package